"""empty message

Revision ID: bedb489957eb
Revises: b1adb8032e7c
Create Date: 2020-08-02 10:16:03.175146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedb489957eb'
down_revision = 'b1adb8032e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dummy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dummy')
    # ### end Alembic commands ###
